# Generated by Django 4.2.4 on 2023-11-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_inoa", "0002_alter_item_nome"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="item", name="frequency", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="item",
            name="lower_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="item",
            name="upper_limit",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
