# Generated by Django 4.2.4 on 2023-11-05 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_inoa", "0003_item_created_at_item_frequency_item_lower_limit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotedPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "high",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "low",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "volume",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "dividends",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                (
                    "stock_splits",
                    models.DecimalField(decimal_places=6, default=0, max_digits=20),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app_inoa.item"
                    ),
                ),
            ],
        ),
    ]
