# Generated by Django 4.2.7 on 2023-11-06 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_inoa", "0004_quotedprice"),
    ]

    operations = [
        migrations.RemoveField(model_name="item", name="name",),
        migrations.DeleteModel(name="MonitoredAsset",),
    ]
