# Generated by Django 4.2.4 on 2023-11-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Meus_ativos",
            fields=[
                ("ticket", models.CharField(max_length=100)),
                ("valor_venda", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("valor_compra", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("valor_fechamento", models.DecimalField(max_digits=10, decimal_places=2, default=0.0))
            ],
        ),
    ]
